enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[Music] #works
enabled = "true"
build-mode = "both"
version = "auto"
arch = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
uptodown-dlurl = "https://youtube-music.fr.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[Music-Extended] #works
enabled = "true"
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://youtube-music.fr.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"

[YouTube] #works
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
version = "auto"
included-patches = "'MaterialYou' 'Visual preferences icons'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[YouTube-Extended] #works
app-name = "YouTube"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Twitter] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
version = "latest"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
excluded-patches = "'Dynamic color'"

[Twitter-material-design] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
version = "latest"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"

[X] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
version = "latest"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
excluded-patches = "'Dynamic color'"

[X-material-design] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
version = "latest"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"

[TikTok] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Reddit-Extended] #maybe?
build-mode = "both"
version = "latest"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://reddit-official-app.fr.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Spotify] #works
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Twitch] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch-app.fr.uptodown.com/android"

[Facebook] #works
build-mode = "both"
version = "auto"
uptodown-dlurl = "https://facebook.fr.uptodown.com/android"
included-patches = "'Predictive back gesture' 'Sproof wi-fi' 'Remove screenshot restriction'"
excluded-patches = "'Hide story ads'"

[Windyapp] #maybe?
build-mode = "both"
version = "auto"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MemeGenerator] #works
build-mode = "both"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
uptodown-dlurl = "https://meme-generator-free.fr.uptodown.com/android"

[Strava] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
uptodown-dlurl = "https://strava.fr.uptodown.com/android"

[Yuka] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
uptodown-dlurl = "https://yuka.fr.uptodown.com/android"

[Transit] #works
patches-source = "andronedev/revanced-patches"
build-mode = "both"
version = "auto"
rv-brand = "andronedev"
uptodown-dlurl = "https://transit.fr.uptodown.com/android"

[Geniusscan]
enabled = "false"
patches-source = "andronedev/revanced-patches"
build-mode = "both"
rv-brand = "andronedev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/the-grizzly-labs/genius-scan-pdf-scanner-2/"
arch = "both"