enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1 

[YouTube] #works
build-mode = "both"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[YouTube-Extended] #works
app-name = "YouTube"
build-mode = "both"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Music-Extended] #works
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[twitter-material-design]
build-mode = "apk"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"

[twitter]
build-mode = "apk"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Bring back twitter' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
excluded-patches = "'Dynamic color'"

[x-material-design]
build-mode = "apk"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"

[x]
build-mode = "apk"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android/"
included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
excluded-patches = "'Dynamic color'"

[TikTok] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Reddit-Extended] #works
build-mode = "both"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://reddit-official-app.fr.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Pixiv] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[Twitch] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch-app.fr.uptodown.com/android"

[MemeGenerator] #works
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
uptodown-dlurl = "https://meme-generator-free.fr.uptodown.com/android"

[Strava] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
uptodown-dlurl = "https://strava.fr.uptodown.com/android"

[Yuka] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
uptodown-dlurl = "https://yuka.fr.uptodown.com/android"

[Photomath] #works
build-mode = "both"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"

[Geniusscan] #works
enabled = "false"
build-mode = "both"
patches-source = "andronedev/revanced-patches"
rv-brand = "andronedev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/the-grizzly-labs/genius-scan-pdf-scanner-2/"
arch = "both"
